const products = [
  { name: 'Smart Automation', description: 'Automatiza procesos repetitivos y reduce el trabajo manual.', problem: 'Procesos manuales', category: 'Automatización', status: 'Disponible', icon: '↗', tone: 'lime' },
  { name: 'Quality Hub', description: 'Mejora la calidad del software mediante testing y automatización.', problem: 'Procesos ineficientes', category: 'Testing y QA', status: 'Disponible', icon: '✓', tone: 'coral' },
  { name: 'Operations Manager', description: 'Centraliza y simplifica la administración de tus procesos y operaciones.', problem: 'Sistemas desconectados', category: 'Administración', status: 'Disponible', icon: '⌘', tone: 'blue' },
  { name: 'Analytics Center', description: 'Monitorea el rendimiento y obtiene información para decidir mejor.', problem: 'Falta de visibilidad', category: 'Analítica', status: 'Beta', icon: '◒', tone: 'yellow' },
  { name: 'AI Assistant', description: 'Utiliza inteligencia artificial para acelerar tareas cotidianas.', problem: 'Crecimiento', category: 'Inteligencia Artificial', status: 'Próximamente', icon: '✦', tone: 'pink' }
];
const metrics = [{ value: '50+', label: 'Soluciones desarrolladas' }, { value: '120K+', label: 'Procesos automatizados' }, { value: '30%', label: 'Reducción de tareas manuales' }, { value: '98%', label: 'Satisfacción de clientes' }];
const features = [{ icon: '↗', title: 'Procesos manuales', text: 'Reduce el tiempo dedicado a tareas repetitivas mediante automatización.', tone: 'lime' }, { icon: '⟷', title: 'Sistemas desconectados', text: 'Conecta herramientas y procesos para centralizar la información.', tone: 'coral' }, { icon: '◉', title: 'Falta de visibilidad', text: 'Obtén información clara para entender y mejorar el rendimiento.', tone: 'blue' }, { icon: '⌁', title: 'Procesos ineficientes', text: 'Identifica oportunidades de mejora y optimiza el trabajo del equipo.', tone: 'yellow' }, { icon: '↗', title: 'Crecimiento', text: 'Construye soluciones que puedan evolucionar junto con tu negocio.', tone: 'pink' }];
const workflow = [{ number: '01', title: 'Entendemos', text: 'Conocemos tu negocio, tus procesos y los retos que enfrentas.' }, { number: '02', title: 'Diseñamos', text: 'Definimos una solución tecnológica adaptada a tus necesidades.' }, { number: '03', title: 'Desarrollamos', text: 'Construimos e integramos software, automatización e inteligencia artificial.' }, { number: '04', title: 'Optimizamos', text: 'Medimos resultados y continuamos mejorando la solución.' }];
const categories = [{ icon: '↗', name: 'Software', text: 'Creamos herramientas digitales que resuelven procesos concretos.' }, { icon: '✓', name: 'Automatización', text: 'Convertimos tareas repetitivas en flujos más eficientes.' }, { icon: '✦', name: 'Inteligencia Artificial', text: 'Amplificamos las capacidades de tus equipos y operaciones.' }, { icon: '⌘', name: 'Integración', text: 'Conectamos tus sistemas para que la información fluya.' }, { icon: '◒', name: 'Analítica', text: 'Transformamos actividad en decisiones inteligentes.' }, { icon: '◉', name: 'Monitoreo', text: 'Hacemos visible el rendimiento de cada proceso.' }];
const testimonials = [{ quote: 'La solución nos permitió reducir significativamente el tiempo que nuestro equipo dedicaba a tareas repetitivas.', name: 'Juan Pérez', role: 'Director de Operaciones', company: 'Empresa XYZ', product: 'Smart Automation', initials: 'JP', tone: 'lime' }, { quote: 'Ahora tenemos una visión clara de la operación y podemos tomar decisiones antes de que los problemas crezcan.', name: 'María González', role: 'Gerente de Operaciones', company: 'Grupo Norte', product: 'Operations Manager', initials: 'MG', tone: 'coral' }, { quote: 'El nuevo flujo de calidad aceleró nuestras entregas y redujo los errores que llegaban a producción.', name: 'Diego Ramírez', role: 'Líder de Producto', company: 'Estudio Delta', product: 'Quality Hub', initials: 'DR', tone: 'blue' }, { quote: 'Con los datos correctos frente a nosotros, las decisiones dejaron de depender de intuiciones.', name: 'Sofía Torres', role: 'Directora de Crecimiento', company: 'Compañía Atlas', product: 'Analytics Center', initials: 'ST', tone: 'yellow' }];

const featureGrid = document.querySelector('#feature-grid');
featureGrid.innerHTML = features.map(item => `<article class="feature-card"><span class="icon-box ${item.tone}">${item.icon}</span><h3>${item.title}</h3><p>${item.text}</p><span class="card-arrow">↗</span></article>`).join('');
document.querySelector('#product-grid').innerHTML = products.map((item, index) => `<article class="product-card ${index === 0 ? 'featured' : ''}"><div class="product-top"><span class="icon-box ${item.tone}">${item.icon}</span><span class="status ${item.status === 'Disponible' ? 'available' : ''}"><i></i>${item.status}</span></div><p class="product-category">${item.category}</p><h3>${item.name}</h3><p>${item.description}</p><p class="product-problem"><b>Ayuda a resolver:</b> ${item.problem}</p><a href="#comenzar" aria-label="Conocer más sobre ${item.name}">Conocer más <span>↗</span></a></article>`).join('');
document.querySelector('#metrics-grid').innerHTML = metrics.map(item => `<div class="metric"><strong>${item.value}</strong><span>${item.label}</span></div>`).join('');
document.querySelector('#workflow-grid').innerHTML = workflow.map((item, index) => `<article class="workflow-step"><div class="step-number">${item.number}</div><h3>${item.title}</h3><p>${item.text}</p>${index < workflow.length - 1 ? '<span class="step-line" aria-hidden="true">→</span>' : ''}</article>`).join('');
document.querySelector('#category-grid').innerHTML = categories.map(item => `<article class="category-card"><span class="category-icon">${item.icon}</span><h3>${item.name}</h3><p>${item.text}</p><span class="card-arrow">↗</span></article>`).join('');
document.querySelector('#testimonial-grid').innerHTML = testimonials.map(item => `<article class="testimonial-card"><div class="stars" aria-label="5 estrellas">★★★★★</div><blockquote>“${item.quote}”</blockquote><div class="person"><span class="avatar ${item.tone}">${item.initials}</span><span><strong>${item.name}</strong><small>${item.role} · ${item.company}</small><small>${item.product}</small></span></div></article>`).join('');

const toggle = document.querySelector('.menu-toggle');
const menu = document.querySelector('.nav-links');
toggle.addEventListener('click', () => { const open = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!open)); menu.classList.toggle('open', !open); });
document.querySelectorAll('.nav-links a').forEach(link => link.addEventListener('click', () => { toggle.setAttribute('aria-expanded', 'false'); menu.classList.remove('open'); }));
const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('visible'); }), { threshold: 0.12 });
document.querySelectorAll('.hero-copy, .feature-card, .product-card, .workflow-step, .category-card, .testimonial-card, .benefit-list > div, .metric').forEach(element => { element.classList.add('reveal'); observer.observe(element); });
